class OpCodes(Enum):

    AGENT_CREATE = 0
    AGENT_GET = 1
    AGENT_DELETE = 2
    AGENT_STEP = 3
    AGENT_SET_STATE = 4
    AGENT_GET_STATE = 5
    AGENT_CURRENT_NODE = 6
    AGENT_PREV_NODE = 7
    AGENT_STRATEGY = 8
    AGENT_STATE = 9
    SENSOR_CREATE = 10
    NEIGHBOR_SENSOR_SENSE = 11
    MAP_SENSOR_SENSE = 12
    AGENT_SENSOR_SENSE = 13
    